 repos:
   - repo: https://github.com/pre-commit/pre-commit-hooks
     rev: v1.3.0
     hooks:
       - id: autopep8-wrapper
       - id: check-byte-order-marker
       - id: check-case-conflict
       - id: check-json
       - id: check-merge-conflict
       - id: check-yaml
       - id: end-of-file-fixer
       - id: flake8
       - id: mixed-line-ending
         args:
           - --fix=lf
       - id: trailing-whitespace
